INSERT INTO haunted_places (name, location, description, history, reported_sightings) VALUES
('Rumah Kentang, Malang', 'Malang, Jawa Timur', 'Rumah angker terkenal dengan bau kentang busuk dan suara tangisan di malam hari.', 'Dulunya rumah ini milik seorang penjual kentang yang meninggal secara misterius.', 'Warga sekitar sering melihat sosok bayangan dan mendengar suara tangisan.'),
('Kebun Raya Bogor', 'Bogor, Jawa Barat', 'Tempat angker yang sering terdengar suara langkah kaki dan bisikan gaib di malam hari.', 'Kebun ini sudah ada sejak masa kolonial dan dipercaya banyak makhluk halus.', 'Pengunjung sering melaporkan suara bisikan dan bayangan.'),
('Rumah Darmo, Surabaya', 'Surabaya, Jawa Timur', 'Rumah peninggalan kolonial yang dikenal dengan penampakan sosok wanita bergaun putih.', 'Dulunya rumah ini milik keluarga kaya yang mengalami tragedi.', 'Sering terlihat sosok wanita dan suara piano misterius.'),
('Hotel Indonesia, Jakarta', 'Jakarta', 'Hotel tua yang konon dihuni oleh arwah tamu yang meninggal secara tragis.', 'Hotel ini pernah menjadi tempat kejadian misterius selama puluhan tahun.', 'Tamu dan staf sering melaporkan penampakan dan suara aneh.'),
('Gunung Lawu', 'Perbatasan Jawa Tengah dan Jawa Timur', 'Gunung dengan cerita mistis dan banyak cerita penampakan makhluk halus.', 'Gunung ini dipercaya sebagai tempat berkumpulnya makhluk gaib.', 'Pendaki sering melihat cahaya dan suara aneh di puncak gunung.'),
('Museum Taman Prasasti, Jakarta', 'Jakarta', 'Museum kuburan kuno dengan cerita arwah yang bergentayangan.', 'Dulunya tempat pemakaman zaman Belanda.', 'Pengunjung melaporkan penampakan sosok berpakaian kuno.'),
('Kota Tua Jakarta', 'Jakarta', 'Area bersejarah dengan cerita tentang arwah penjaga kota.', 'Pusat aktivitas Belanda tempo dulu dengan banyak tragedi.', 'Orang sering mendengar suara langkah dan bisikan.'),
('Rumah Setan Kampung Melayu', 'Jakarta Timur', 'Rumah yang dikenal penuh aktivitas gaib dan penampakan.', 'Dulu pernah terjadi pembunuhan misterius.', 'Warga sering melihat bayangan dan mendengar jeritan.'),
('Benteng Van Der Wijck, Jawa Tengah', 'Kutoarjo, Jawa Tengah', 'Benteng peninggalan Belanda dengan cerita angker yang cukup terkenal.', 'Benteng ini menjadi saksi bisu berbagai peristiwa berdarah.', 'Sering terdengar suara tentara berbaris dan suara tembakan.'),
('Gedung Lawang Sewu, Semarang', 'Semarang, Jawa Tengah', 'Gedung tua dengan banyak lorong dan cerita hantu yang melegenda.', 'Dulunya markas tentara Belanda dan penjara.', 'Pengunjung melaporkan penampakan dan suara aneh.');
